### ISSUE TITLE
RELEASE DATE

### ISSUE THREAD

**Issue by 7Frost7** [BinBashBanana/badrecovery#3] opened 2024-10-04 15:17 UTC
Olybmmer has a wrong release date

**Comment by kkilobyte** [comment] 2024-10-04 23:23
duplicate of #2

**Comment by liujustin604** [comment] 2024-10-05 01:10
> duplicate of #2

how is an issue a duplicate of a PR?

**Comment by kkilobyte** [comment] 2024-10-05 01:43
> how is an issue a duplicate of a PR?
the PR fixes the issue

**Comment by liujustin604** [comment] 2024-10-05 12:25
> > how is an issue a duplicate of a PR?
> 
> 
> 
> the PR fixes the issue

then it should be marked as such, and not as a duplicate

**Comment by SilverGamer5934** [comment] 2024-10-05 21:58
Oily boomer please release

**Closed** 2024-10-06 00:22 UTC
